FROM ubuntu:18.04

MAINTAINER michele.gazzetti1@ibm.com


RUN apt update && apt install build-essential -y

ADD . /libthymesisflow
WORKDIR /libthymesisflow

# on x86 we support only the mocking
RUN make MOCK=1 && \
    cp ./bin/thymesisf-agent /usr/bin/ && \
    chmod +x /usr/bin/thymesisf-agent

CMD ["/usr/bin/thymesisf-agent"]
